ReadHouseOnline/Controllers/CarouselAreaController.cs
using RHF.Business.Models.RHF;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ReadHouseOnline.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public class CarouselAreaController : Controller
	{
		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			this.CarouselBooksInit();

			return PartialView("~/Views/Shared/User/CarouselArea.cshtml");
		}

		/// <summary>
		/// 
		/// </summary>
		private void CarouselBooksInit()
		{
			this.ViewData.Add("active", new List<T_Book>()
									{
										new T_Book(){ ID = 1,  Name = "001", Description = "~/Content/image/books/001.jpg" },
										new T_Book(){ ID = 1,  Name = "002", Description = "~/Content/image/books/002.jpg" },
										new T_Book(){ ID = 1,  Name = "003", Description = "~/Content/image/books/003.jpg" },
										new T_Book(){ ID = 1,  Name = "004", Description = "~/Content/image/books/004.jpg" },
										new T_Book(){ ID = 1,  Name = "005", Description = "~/Content/image/books/005.jpg" },
										new T_Book(){ ID = 1,  Name = "006", Description = "~/Content/image/books/006.jpg" },
										new T_Book(){ ID = 1,  Name = "007", Description = "~/Content/image/books/007.jpg" },
										new T_Book(){ ID = 1,  Name = "008", Description = "~/Content/image/books/008.jpg" },
										new T_Book(){ ID = 1,  Name = "009", Description = "~/Content/image/books/009.jpg" },
										new T_Book(){ ID = 1,  Name = "010", Description = "~/Content/image/books/010.jpg" },
									});

			this.ViewData.Add("carousel1", new List<T_Book>()
									{
										new T_Book(){ ID = 1,  Name = "001", Description = "~/Content/image/books/011.jpg" },
										new T_Book(){ ID = 1,  Name = "002", Description = "~/Content/image/books/012.jpg" },
										new T_Book(){ ID = 1,  Name = "003", Description = "~/Content/image/books/013.jpg" },
										new T_Book(){ ID = 1,  Name = "004", Description = "~/Content/image/books/014.jpg" },
										new T_Book(){ ID = 1,  Name = "005", Description = "~/Content/image/books/015.jpg" },
										new T_Book(){ ID = 1,  Name = "006", Description = "~/Content/image/books/008.jpg" },
										new T_Book(){ ID = 1,  Name = "007", Description = "~/Content/image/books/016.jpg" },
										new T_Book(){ ID = 1,  Name = "008", Description = "~/Content/image/books/017.jpg" },
										new T_Book(){ ID = 1,  Name = "009", Description = "~/Content/image/books/018.jpg" },
										new T_Book(){ ID = 1,  Name = "010", Description = "~/Content/image/books/019.jpg" },
									});

			this.ViewData.Add("carousel2", new List<T_Book>()
									{
										new T_Book(){ ID = 1,  Name = "001", Description = "~/Content/image/books/023.jpg" },
										new T_Book(){ ID = 1,  Name = "002", Description = "~/Content/image/books/022.jpg" },
										new T_Book(){ ID = 1,  Name = "003", Description = "~/Content/image/books/014.jpg" },
										new T_Book(){ ID = 1,  Name = "004", Description = "~/Content/image/books/016.jpg" },
										new T_Book(){ ID = 1,  Name = "005", Description = "~/Content/image/books/007.jpg" },
										new T_Book(){ ID = 1,  Name = "006", Description = "~/Content/image/books/008.jpg" },
										new T_Book(){ ID = 1,  Name = "007", Description = "~/Content/image/books/019.jpg" },
										new T_Book(){ ID = 1,  Name = "008", Description = "~/Content/image/books/005.jpg" },
										new T_Book(){ ID = 1,  Name = "009", Description = "~/Content/image/books/008.jpg" },
										new T_Book(){ ID = 1,  Name = "010", Description = "~/Content/image/books/006.jpg" },
									});
		}
	}
}

ReadHouseOnline/Controllers/HomeController.cs
using RHF.Business.BLL.Parameters;
using RHF.Business.Models.RHF;
using RHF.Core.BusinessLogic;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace ReadHouseOnline.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	public class HomeController : Controller
	{
		/// <summary>
		/// 
		/// </summary>
		private LogicExecuteHelper _LogicHelper;

		/// <summary>
		/// 
		/// </summary>
		protected LogicExecuteHelper LogicHelper
		{
			get
			{
				if (_LogicHelper == null)
				{
					_LogicHelper = new LogicExecuteHelper();
				}
				return _LogicHelper;
			}
		}

		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		public ActionResult Index()
		{
			var member = new T_Member();
			return View(member);
		}

		/// <summary>
		/// 
		/// </summary>
		/// <param name="member"></param>
		/// <returns></returns>
		[HttpPost]
		public ActionResult Index(T_Member member)
		{
			if (ModelState.IsValid)
			{
				var logic = LogicHelper.CreateLogic("Login");
				var bcp = (LoginBcp)LogicHelper.LogicFactory.CreateParameter("Login");

				bcp.EMail = member.Email;
				bcp.Password = member.Password;
				logic.Execute(bcp);

				if (bcp.IsLogin)
				{
					var authTicket = new FormsAuthenticationTicket(1, member.Email, DateTime.Now, DateTime.Now.AddMinutes(10), true, "/");

					string encryptedTicket = FormsAuthentication.Encrypt(authTicket);

					var authCookie = new HttpCookie(FormsAuthentication.FormsCookieName, encryptedTicket)
					{
						HttpOnly = true
					};
					Response.Cookies.Add(authCookie);

					return Redirect(Url.Action("Index", "Main"));
				}
				else
				{
					return JavaScript(@"RHF.Login.showMessage('" + bcp.Messages.ElementAt(0).Message + "');");
				}
			}

			return View(member);
		}
	}
}

ReadHouseOnline/Controllers/MainController.cs
using System.Web.Mvc;
using System.Web.Security;

namespace ReadHouseOnline.Controllers
{
	/// <summary>
	/// 
	/// </summary>
	[Authorize]
	public class MainController : Controller
	{
		//
		// GET: /Main/

		public ActionResult Index()
		{
			return View();
		}

		/// <summary>
		/// 
		/// </summary>
		/// <returns></returns>
		public ActionResult LogOut()
		{
			// 通過Forms驗證來刪除Cookie
			FormsAuthentication.SignOut();

			return Redirect(Url.Action("Index", "Main"));
		}
	}
}

ReadHouseOnline/Views/Home/Index.cshtml
@using System.Web.Mvc.Html;
@using RHF.Business.Models.RHF;
@model T_Member
@{
	ViewBag.Title = "读书小站";
	Layout = "~/Views/Shared/_Login.cshtml";
}

@section head 
{
	<script type="text/javascript" src="@Url.Content("~/Scripts/extends/RHF.Login.js")"></script>
	<script type="text/javascript">
		$(document).ready(function () {
			$("#logoImg").fadeIn(3000);

			formValidate();
		});

		var formValidate = function () {
			$("#loginForm").validate({
				focusInvalid: false,
                onblur: true,
				focusCleanup: true,
                errorElement: "span",
				rules: {
					Email: {
						required: true,
						email: true
					},
					Password: {
						required: true,
                        rangelength: [6, 8],
					}
				},
				messages: {
					Email: {
						required: "用戶名不能為空",
						email: "E-Mail格式不正確"
					},
					Password: {
                        required: "密碼不能為空",
                        rangelength: "密碼長度為6-8位"
					}
				},
				errorPlacement: function (error, element) {
					error.appendTo(element.parent().next());
				}
			})
		};
	</script>
}

<div class="container">
	@using (Html.BeginForm("Index", "Home", FormMethod.Post, new { id = "loginForm" }))
 {
		@Html.AntiForgeryToken()
		@Html.ValidationSummary(true)

		<div style="padding-top: 30px;" class="row">
			<div class="col-xs-3 col-md-2"></div>
			<div class="col-xs-6 col-md-3">
				<img id="logoImg" class="logoImg" src="~/Content/image/logobg.png">
			</div>
			<div class="col-xs-3 col-md-7"></div>
		</div>
		<div style="padding-top: 5px;" class="row">
			<div class="col-xs-2 col-md-2"></div>
			<div class="col-xs-2 col-md-2">
				<p class="text-right">
					<label class="text-muted h5" for="Email">账号</label>
				</p>
			</div>
			<div class="col-xs-3 col-md-3">
				@Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "邮箱/用户名", type = "email" })
			</div>
			<div class="col-xs-5 col-md-5">
					@Html.ValidationMessageFor(m => m.Email)
			</div>
		</div>
		<div style="padding-top: 3px;" class="row">
			<div class="col-xs-2 col-md-2"></div>
			<div class="col-xs-2 col-md-2">
				<p class="text-right">
					<label class="text-muted h5" for="Password">密码</label>
				</p>
			</div>
			<div class="col-xs-2 col-md-2">
				@Html.PasswordFor(m => m.Password, new { @class = "form-control", placeholder = "密码" })
			</div>
			<div class="col-xs-6 col-md-6">
					@Html.ValidationMessageFor(m => m.Password)
			</div>
		</div>
		<div class="row">
			<div class="col-xs-4 col-md-4"></div>
			<div class="col-xs-4 col-md-4">
				<div class="checkbox">
					<label>
						@Html.CheckBox("chkNext", false, new { @class = "checkBox" })
						下次自动登录
					</label>
				</div>
			</div>
			<div class="col-xs-4 col-md-4"></div>
		</div>
		<div class="row">
			<div class="col-xs-4 col-md-4"></div>
			<div class="col-xs-4 col-md-4">
				<button type="submit" id="btnLogin" class="btn btn-success">登录</button>
			</div>
			<div class="col-xs-4 col-md-4"></div>
		</div>
 }
	<div class="row">
		<div class="col-xs-4 col-md-4"></div>
		<div class="col-xs-4 col-md-4">
			<h6 class="text-success">&gt; 还没有账号？
					<a href="###">立即注册</a>
			</h6>
		</div>
		<div class="col-xs-4 col-md-4"></div>
	</div>
</div>

ReadHouseOnline/Views/Main/Index.cshtml
@using System.Web.Mvc.Html;
@using RHF.Business.Models.RHF;
@{
	Layout = null;
}

<!DOCTYPE html>

<html lang="zh-cn">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width" />
	<title>读书小站</title>
	<link rel="stylesheet" href="~/Content/css/bootstrap.min.css">
	<link rel="stylesheet" href="~/Content/css/extends/main.css">
	<script type="text/javascript" src="~/Scripts/jquery-2.2.3.min.js"></script>
	<script type="text/javascript" src="~/Scripts/bootstrap.min.js"></script>
	<script type="text/javascript">
		$(document).ready(function () {
		});
	</script>
</head>
<body role="document">
	<nav class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">读书小站</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					<li><a href="#about">登录</a></li>
					<li><a href="#contact">注册</a></li>
					<li role="presentation"><a href="#">提醒 <span class="badge">4</span></a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Tony的账号 <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#">个人主页</a></li>
							<li><a href="#">账号管理</a></li>
							<li role="separator" class="divider"></li>
                            <li>@Html.ActionLink("退出", "LogOut", "Main")</li>
						</ul>
					</li>
				</ul>
			</div>
			<!--/.nav-collapse -->
		</div>
	</nav>
</body>
</html>

ReadHouseOnline/Views/Shared/User/CarouselArea.cshtml
@using RHF.Business.Models.RHF;
<script type="text/javascript" src="@Url.Content("~/Scripts/extends/RHF.Login.js")"></script>
<script type="text/javascript">
	$(document).ready(function () {
		$("#divCarouselArea").fadeIn(600, function () {
			$("#divCarousel").carousel('cycle');
		});

		RHF.Login.imageProgramaDisplay();
	});
</script>

<div id="divCarouselArea" class="row" style="display: none;">
	<div class="col-xs-1 col-md-1"></div>
	<div class="col-xs-10 col-md-10 center-block">
		<div id="divCarousel" class="carousel slide">
			<!-- 轮播（Carousel）指标 -->
			<ol class="carousel-indicators">
				<li data-target="#divCarousel" data-slide-to="0" class="active"></li>
				<li data-target="#divCarousel" data-slide-to="1"></li>
				<li data-target="#divCarousel" data-slide-to="2"></li>
			</ol>
			<!-- 轮播（Carousel）项目 -->
			<div class="carousel-inner">
				<div class="item active">
					@foreach (var item in ViewData["active"] as List<T_Book>)
	 {
						<div class="imageTag">
							<div class="tagItem">
								<a href="###">
									<img src="@Url.Content(item.Description)">
								</a>
							</div>
						</div>
	 }
				</div>
				<div class="item">
					@foreach (var item in ViewData["carousel1"] as List<T_Book>)
	 {
						<div class="imageTag">
							<div class="tagItem">
								<a href="###">
									<img src="@Url.Content(item.Description)">
								</a>
							</div>
						</div>
	 }
				</div>
				<div class="item">
					@foreach (var item in ViewData["carousel2"] as List<T_Book>)
	 {
						<div class="imageTag">
							<div class="tagItem">
								<a href="###">
									<img src="@Url.Content(item.Description)">
								</a>
							</div>
						</div>
	 }
				</div>
			</div>
		</div>
	</div>
	<div class="col-xs-1 col-md-1"></div>
</div>

ReadHouseOnline/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html lang="zh-cn">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width" />
	<title>@ViewBag.Title</title>
	<link rel="stylesheet" href="@Url.Content("~/Content/css/bootstrap.min.css")" type="text/css">
	<link rel="stylesheet" href="@Url.Content("~/Content/css/extends/login.css")" type="text/css">
	<script type="text/javascript" src="@Url.Content("~/Scripts/jquery-2.2.3.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
	<script type="text/javascript" src="@Url.Content("~/Scripts/jquery.validate.js")"></script>
	@RenderSection("head", required: false)
</head>
<body>
    @RenderBody()

    <div class="modal fade bd-example-modal-sm" id="myModal" role="dialog" data-backdrop="false" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <p class="text-center mb-0">
                    <h2>
                        <i class="fa fa-check-circle text-success mr-3" aria-hidden="true"></i>
                        <span id="spanMsg"></span>
                    </h2>
                </p>
            </div>
        </div>
    </div>

    @RenderSection("scripts", required: false)
</body>
</html>

ReadHouseOnline/Views/Shared/_Login.cshtml
@using System.Web.Mvc.Html;
@{
	Layout = "~/Views/Shared/_Layout.cshtml";
}

@RenderSection("head", required: false)

<div class="container">
	@RenderBody()

	@{ Html.RenderAction("Index", "CarouselArea"); }

	<div class="modal-footer">
		<h6>@Html.Raw("@2016 - 2018 RHF.com, all right reserved")</h6>
	</div>

	@RenderSection("scripts", required: false)
</div>